# Generated by Django 5.1 on 2024-08-19 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('relationship_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='library',
            old_name='books',
            new_name='book',
        ),
    ]
