# Generated by Django 5.1 on 2024-08-28 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relationship_app', '0002_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('Admin', 'ADMIN'), ('librarian', 'LIBRARIAN'), ('Member', 'MEMBER')], default='admin', max_length=200),
        ),
    ]
